import { IAsyncCall } from '@Root/types';

export const FETCH_ALL_RISKS_REQUESTED = 'FETCH_ALL_RISKS/REQUESTED';
export const FETCH_ALL_RISKS_SUCCESS = 'FETCH_ALL_RISKS/SUCCESS';
export const FETCH_ALL_RISKS_FAILURE = 'FETCH_ALL_RISKS/FAILURE';

export const ASYNC_FETCH_ALL_RISKS: IAsyncCall = {
  REQUESTED: FETCH_ALL_RISKS_REQUESTED,
  SUCCESS: FETCH_ALL_RISKS_SUCCESS,
  FAILURE: FETCH_ALL_RISKS_FAILURE,
};

//defined add risk
export const ADD_RISKS_REQUESTED = 'ADD_RISKS/REQUESTED';
export const ADD_RISKS_SUCCESS = 'ADD_RISKS/SUCCESS';
export const ADD_RISKS_FAILURE = 'ADD_RISKS/FAILURE';

export const ASYNC_ADD_RISKS: IAsyncCall = {
  REQUESTED: ADD_RISKS_REQUESTED,
  SUCCESS: ADD_RISKS_SUCCESS,
  FAILURE: ADD_RISKS_FAILURE,
};

//defined edit risk
export const EDIT_RISKS_REQUESTED = 'EDIT_RISKS/REQUESTED';
export const EDIT_RISKS_SUCCESS = 'EDIT_RISKS/SUCCESS';
export const EDIT_RISKS_FAILURE = 'EDIT_RISKS/FAILURE';

export const ASYNC_EDIT_RISKS: IAsyncCall = {
  REQUESTED: EDIT_RISKS_REQUESTED,
  SUCCESS: EDIT_RISKS_SUCCESS,
  FAILURE: EDIT_RISKS_FAILURE,
};

//defined filter
export const FILTER_RISKS_REQUESTED = 'FILTER_RISKS/REQUESTED';
export const FILTER_RISKS_SUCCESS = 'FILTER_RISKS/SUCCESS';
export const FILTER_RISKS_FAILURE = 'FILTER_RISKS/FAILURE';

export const ASYNC_FILTER_RISKS: IAsyncCall = {
  REQUESTED: FILTER_RISKS_REQUESTED,
  SUCCESS: FILTER_RISKS_SUCCESS,
  FAILURE: FILTER_RISKS_FAILURE,
};