import { IAsyncCall } from '@Root/types';

export const FETCH_ALL_PROCEDURES_REQUESTED = 'FETCH_ALL_PROCEDURES/REQUESTED';
export const FETCH_ALL_PROCEDURES_SUCCESS = 'FETCH_ALL_PROCEDURES/SUCCESS';
export const FETCH_ALL_PROCEDURES_FAILURE = 'FETCH_ALL_PROCEDURES/FAILURE';

export const ASYNC_FETCH_ALL_PROCEDURES: IAsyncCall = {
  REQUESTED: FETCH_ALL_PROCEDURES_REQUESTED,
  SUCCESS: FETCH_ALL_PROCEDURES_SUCCESS,
  FAILURE: FETCH_ALL_PROCEDURES_FAILURE,
};

//defined add procedure
export const ADD_PROCEDURES_REQUESTED = 'ADD_PROCEDURES/REQUESTED';
export const ADD_PROCEDURES_SUCCESS = 'ADD_PROCEDURES/SUCCESS';
export const ADD_PROCEDURES_FAILURE = 'ADD_PROCEDURES/FAILURE';

export const ASYNC_ADD_PROCEDURES: IAsyncCall = {
  REQUESTED: ADD_PROCEDURES_REQUESTED,
  SUCCESS: ADD_PROCEDURES_SUCCESS,
  FAILURE: ADD_PROCEDURES_FAILURE,
};

//defined edit procedure
export const EDIT_PROCEDURES_REQUESTED = 'EDIT_PROCEDURES/REQUESTED';
export const EDIT_PROCEDURES_SUCCESS = 'EDIT_PROCEDURES/SUCCESS';
export const EDIT_PROCEDURES_FAILURE = 'EDIT_PROCEDURES/FAILURE';

export const ASYNC_EDIT_PROCEDURES: IAsyncCall = {
  REQUESTED: EDIT_PROCEDURES_REQUESTED,
  SUCCESS: EDIT_PROCEDURES_SUCCESS,
  FAILURE: EDIT_PROCEDURES_FAILURE,
};

//defined filter
export const FILTER_PROCEDURES_REQUESTED = 'FILTER_PROCEDURES/REQUESTED';
export const FILTER_PROCEDURES_SUCCESS = 'FILTER_PROCEDURES/SUCCESS';
export const FILTER_PROCEDURES_FAILURE = 'FILTER_PROCEDURES/FAILURE';

export const ASYNC_FILTER_PROCEDURES: IAsyncCall = {
  REQUESTED: FILTER_PROCEDURES_REQUESTED,
  SUCCESS: FILTER_PROCEDURES_SUCCESS,
  FAILURE: FILTER_PROCEDURES_FAILURE,
};