import { IAsyncCall } from '@Root/types';

export const FETCH_ALL_PROCEDURES_REQUESTED = 'FETCH_ALL_RISKS/REQUESTED';
export const FETCH_ALL_PROCEDURES_SUCCESS = 'FETCH_ALL_PROCEDURES/SUCCESS';
export const FETCH_ALL_PROCEDURES_FAILURE = 'FETCH_ALL_PROCEDURES/FAILURE';

export const ASYNC_FETCH_ALL_PROCEDURES: IAsyncCall = {
  REQUESTED: FETCH_ALL_PROCEDURES_REQUESTED,
  SUCCESS: FETCH_ALL_PROCEDURES_SUCCESS,
  FAILURE: FETCH_ALL_PROCEDURES_FAILURE,
};