export const COLORS = {
    greenColor: '#3AB77B',
    lightGreenColor: '#BFEBD6',
    blueColor: '#3B5AA1',
    redColor: '#E9645B',
    lightRedColor: '#FBE0DE',
    orangeColor: '#E0A60F',
    lightOrangeColor: '#F4E490',
    whiteColor: '#FFFFFF',
    greyColor: '#A2A8B4',
    lightGreyColor: '#F4F4F4',
    darkGreyColor: '#6E7687',
    lightBlackColor: '#35415C',
    whiteSmokeColor: '#f5f5f5',
    blackColor: '#000000',
    silverFoilColor: '#AEAEAE',
    grayishBlueColor: '#656A74',
    brightGreenColor: '#3AB77B',
    platinumColor: '#E4E4E4',
    philippineGrayColor: '#8F8F8F',
};