import { IAsyncCall } from '@Root/types';

export const FETCH_ALL_BENEFITS_REQUESTED = 'FETCH_ALL_BENEFITS/REQUESTED';
export const FETCH_ALL_BENEFITS_SUCCESS = 'FETCH_ALL_BENEFITS/SUCCESS';
export const FETCH_ALL_BENEFITS_FAILURE = 'FETCH_ALL_BENEFITS/FAILURE';

export const ASYNC_FETCH_ALL_BENEFITS: IAsyncCall = {
  REQUESTED: FETCH_ALL_BENEFITS_REQUESTED,
  SUCCESS: FETCH_ALL_BENEFITS_SUCCESS,
  FAILURE: FETCH_ALL_BENEFITS_FAILURE,
};

//defined add benefit
export const ADD_BENEFITS_REQUESTED = 'ADD_BENEFITS/REQUESTED';
export const ADD_BENEFITS_SUCCESS = 'ADD_BENEFITS/SUCCESS';
export const ADD_BENEFITS_FAILURE = 'ADD_BENEFITS/FAILURE';

export const ASYNC_ADD_BENEFITS: IAsyncCall = {
  REQUESTED: ADD_BENEFITS_REQUESTED,
  SUCCESS: ADD_BENEFITS_SUCCESS,
  FAILURE: ADD_BENEFITS_FAILURE,
};

//defined edit benefit
export const EDIT_BENEFITS_REQUESTED = 'EDIT_BENEFITS/REQUESTED';
export const EDIT_BENEFITS_SUCCESS = 'EDIT_BENEFITS/SUCCESS';
export const EDIT_BENEFITS_FAILURE = 'EDIT_BENEFITS/FAILURE';

export const ASYNC_EDIT_BENEFITS: IAsyncCall = {
  REQUESTED: EDIT_BENEFITS_REQUESTED,
  SUCCESS: EDIT_BENEFITS_SUCCESS,
  FAILURE: EDIT_BENEFITS_FAILURE,
};

//defined filter
export const FILTER_BENEFITS_REQUESTED = 'FILTER_BENEFITS/REQUESTED';
export const FILTER_BENEFITS_SUCCESS = 'FILTER_BENEFITS/SUCCESS';
export const FILTER_BENEFITS_FAILURE = 'FILTER_BENEFITS/FAILURE';

export const ASYNC_FILTER_BENEFITS: IAsyncCall = {
  REQUESTED: FILTER_BENEFITS_REQUESTED,
  SUCCESS: FILTER_BENEFITS_SUCCESS,
  FAILURE: FILTER_BENEFITS_FAILURE,
};